local ncbclassic = {
    name = "Classic",
    frame = {
        height = 32,
        width = 256,
    },
    background = {
        texture = "Interface\\Addons\\NugComboBar\\textures\\oldstyle\\NCBBackground",
        height = 32,
        width = 256,
        offsetX = 0,
        offsetY = 0,
    },
    points = {
        [1] = {
            height = 13,
            width = 13,
            offsetX = 71,
            offsetY = -8,
            texture = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\oldstyle\\NCBPoint",
                height = 12,
                width = 12,
                offsetX = 2,
                offsetY = 0,
            },
            highlight = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\oldstyle\\NCBShine",
                height = 16,
                width = 16,
                offsetX = 3,
                offsetY = 4,
            },
        },
        [2] = {
            height = 13,
            width = 13,
            offsetX = 24,
            offsetY = 0,
            texture = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\oldstyle\\NCBPoint",
                height = 12,
                width = 12,
                offsetX = 2,
                offsetY = 0,
            },
            highlight = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\oldstyle\\NCBShine",
                height = 16,
                width = 16,
                offsetX = 3,
                offsetY = 4,
            },
        },
        [3] = {
            height = 13,
            width = 13,
            offsetX = 24,
            offsetY = 0,
            texture = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\oldstyle\\NCBPoint",
                height = 12,
                width = 12,
                offsetX = 2,
                offsetY = 0,
            },
            highlight = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\oldstyle\\NCBShine",
                height = 16,
                width = 16,
                offsetX = 3,
                offsetY = 4,
            },
        },
        [4] = {
            height = 13,
            width = 13,
            offsetX = 23,
            offsetY = 0,
            texture = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\oldstyle\\NCBPoint",
                height = 12,
                width = 12,
                offsetX = 2,
                offsetY = 0,
            },
            highlight = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\oldstyle\\NCBShine",
                height = 16,
                width = 16,
                offsetX = 3,
                offsetY = 4,
            },
        },
        [5] = {
            height = 17,
            width = 17,
            offsetX = 27,
            offsetY = 0,
            texture = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\oldstyle\\NCBPoint",
                height = 16,
                width = 16,
                offsetX = 2,
                offsetY = 0,
            },
            highlight = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\oldstyle\\NCBShine",
                height = 20,
                width = 20,
                offsetX = 3,
                offsetY = 4,
            },
        },
    },
}

local striped = {
    name = "Striped",
    frame = {
        height = 64,
        width = 256,
    },
    background = {
        texture = "Interface\\Addons\\NugComboBar\\textures\\striped\\StripedBG",
        height = 64,
        width = 256,
        offsetX = 0,
        offsetY = 0,
    },
    points = {
        [1] = {
            height = 64,
            width = 64,
            offsetX = 49,
            offsetY = 0,
            texture = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\striped\\StripedPT",
                height = 64,
                width = 64,
                offsetX = 2,
                offsetY = 0,
            },
            highlight = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\striped\\StripedSN",
                height = 64,
                width = 64,
                offsetX = 3,
                offsetY = 4,
            },
        },
        [2] = {
            height = 64,
            width = 64,
            offsetX = 22,
            offsetY = 0,
            texture = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\striped\\StripedPT",
                height = 64,
                width = 64,
                offsetX = 2,
                offsetY = 0,
            },
            highlight = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\striped\\StripedSN",
                height = 64,
                width = 64,
                offsetX = 3,
                offsetY = 4,
            },
        },
        [3] = {
            height = 64,
            width = 64,
            offsetX = 22,
            offsetY = 0,
            texture = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\striped\\StripedPT",
                height = 64,
                width = 64,
                offsetX = 2,
                offsetY = 0,
            },
            highlight = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\striped\\StripedSN",
                height = 64,
                width = 64,
                offsetX = 3,
                offsetY = 4,
            },
        },
        [4] = {
            height = 64,
            width = 64,
            offsetX = 22,
            offsetY = 0,
            texture = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\striped\\StripedPT",
                height = 64,
                width = 64,
                offsetX = 2,
                offsetY = 0,
            },
            highlight = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\striped\\StripedSN",
                height = 64,
                width = 64,
                offsetX = 3,
                offsetY = 4,
            },
        },
        [5] = {
            height = 64,
            width = 64,
            offsetX = 23,
            offsetY = 0,
            texture = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\striped\\StripedPT",
                height = 64,
                width = 64,
                offsetX = 2,
                offsetY = 0,
            },
            highlight = {
                texture = "Interface\\Addons\\NugComboBar\\textures\\striped\\StripedSN",
                height = 64,
                width = 64,
                offsetX = 3,
                offsetY = 4,
            },
        },
    },
}

NugComboBarSkins = NugComboBarSkins or {}
NugComboBarSkins["NCB Classic"] = ncbclassic
NugComboBarSkins["Striped"] = striped
